package com.literallyprofessional.dnd.core

/**
 * Enum representing the various skills in game
 */
enum Skill implements Serializable{
    APPRAISE, BALANCE, BLUFF, CLIMB,
    CONCENTRATION, CRAFT, DECIPHER_SCRIPT,
    DIPLOMACY, DISABLE_DEVICE, DISGUISE,
    ESCAPE_ARTIST, FORGERY, GATHER_INFO,
    HANDLE_ANIMAL, HEAL, HIDE, INTIMIDATE,
    JUMP, KNOW_ARCANA, KNOW_ARCH_ENG,
    KNOW_DUNGEONEERING, KNOW_GEOGRAPHY,
    KNOW_HISTORY, KNOW_LOCAL, KNOW_NATURE,
    KNOW_NOBLE_ROYAL, KNOW_RELIGION,
    KNOW_PLANES, LISTEN, MOVE_SILENTLY,
    OPEN_LOCK, PERFORM, PROFESSION, RIDE,
    SEARCH, SENSE_MOTIVE, SLEIGHT_OF_HAND,
    SPEAK_LANGUAGE, SPELLCRAFT, SPOT,
    SWIM, TUMBLE, USE_MAGIC_DEVICE,
    USE_ROPE,
}
